### ISSUE TITLE
Editor - Save doesn't persist scene changes

### ISSUE THREAD

**Issue by carlfravel** [decentraland/editor-legacy#8]
Save and reload of scene does not get the changes back.

// Steps to repro
Create new scene
Move or delete boilerplate objects
Save scene
Capture the hash number
Close editor
Open editor on the same using the URL with the scene name
// expect: see changes
// actual: see original boilerplate
Open editor on the same using the URL with the scene hash
// expect: see changes
// actual: see original boilerplate

**Comment by carlfravel** [comment]
Here is a specific case of saving not persisting the changes (or scene loader doesn’t load them)
Carl started a New Scene, called CarlFravelTest1, in the DCL Editor
    https://editor.decentraland.org/scene/CarlFravelTest1 
Carl and Dave both made some changes to the boilerplate scene.
Carl clicked Save
// Binding Scene Name to Hash
// The IPNS locator is: /ipns/CarlFravelTest1
// The IPFS hash pointed to is: QmcJZ49TPkMHvQLCp35D5WF6N7KHoYVEyAHSg8yz6TuqaN
Carl and Dave closed the scene, waited 20 seconds
Carl and Dave reopened Scene CarlFravelTest1, using
    https://editor.decentraland.org/scene/CarlFravelTest1
// expected: Both to see the modified scene
// actual: Carl saw original boilerplate scene
// actual: Dave saw things missing that he had deleted, not the boilerplate nor the saved scene
We also tried opening it via hash URL
    https://editor.decentraland.org/scene/QmcJZ49TPkMHvQLCp35D5WF6N7KHoYVEyAHSg8yz6TuqaN
// again, saw original boillerplate, no changes

Subsequent opening of same scene URL and another save gave me a new and different hash
The IPNS locator is: /ipns/CarlFravelTest1
The IPFS hash pointed to is: QmYWeqNrv3KtakHwLjHw2MANyTo56PrSP2LJ1ABY6T5aPm

**Comment by carlfravel** [comment]
Two other cases:

https://editor.decentraland.org/scene/dave_test
Saved
The IPNS locator is: /ipns/dave_test
The IPFS hash pointed to is: QmQonmWjTm78DKKaNZsG4zTkvtjG8MP5rZXoUy7tqGFWag

https://editor.decentraland.org/scene/carl_dave
Scene "carl_dave" saved to IPFS
First time explicitly saved:
The IPNS locator is: /ipns/carl_dave
The IPFS hash pointed to is: QmaAZpZ7URSkeqfZHwepr9ZYNnYxX4gmBxdGE9vajgZrAc

**Comment by cfravel** [comment]
Verified fixed

Here is my test script, using the latest editor.

In Blender, I opened an existing .blend file
// I used sci fi space cargo box
Selected the object in Blender to export // only required if Blender scene has multiple objects
File - Export - Wavefront OBJ
In the options, set
Forward = -Z Forward   
Up = Y Up
(because that is the coordination system that A-Frame uses)
Also turned on the following options
Selection Only (if you had more than one object in Blender, and selected the one you want to export)
Triangulate Faces
Apply Modifiers
Include Edges
Write Normals
Include UVs
Write Materials
Objects as OBJ Objects

https://editor.decentraland.org
Start new scene named
https://editor.decentraland.org/scene/CarlFravelTest-2017-11-12-1949

// In the Editor:
// notice that the parcel objects are <a-box parcel-n> where n is 2-, <a-obj-model parcel-8>

Delete middle blue box <a-box parcel-3>
Move top blue box <a-box parcel-4> from <0, 5.737, -2.720> to <2.0, 5.737, -2.720>
In the Scene Graph panel on the left, under Add..., click .obj

In the Component panel on the right, enter an ID for this object 
// e.g. ID: crate-zUp-xFwd
// notice that the new object has been renamed to <a-object-model crate-zUp-xFwd> in the Scenegraph
In the component frame, clicked on mtl black rectangle
Picked the mtl and png files from my desk
Waited about 7 seconds
// the path filled in, with:
// https://gateway.ipfs.io/ipfs/QmZTVwqB8LZ9fEfEqyZLTFrJidiZB9Zaqbd3StXQSVTMHv/sci_fi_space_cargo_container_3 - Zup-XForward.mtl
Clicked on the obj black rectangle
Picked the obj files from my desk
Waited a few seconds
// the path filled in, with:
// https://gateway.ipfs.io/ipfs/QmZrDFCTnoVxMh9DjG4kRNhJ8PyrTk3RjYnRejfasqVeQc/sci_fi_space_cargo_container_3 - Zup-XForward.obj
// expected: object is rendered in scene
// actual: object not rendered in scene, still just shows its slection tool

Save
// Scene "CarlFravelTest-2017-11-12-1949" saved to IPFS
// The IPNS locator is: /ipns/Qmcnc43usGQiXUwPNN1xoTV9MCn1Dy9mqbsqpmcwx25FUc
// The IPFS hash pointed to is: QmZ7WvSM61TWWfrwATRPRJJdWck29MJ5sgsydkDMGwkbxV

Continue Editing

// Reopened https://editor.decentraland.org/scene/CarlFravelTest-2017-11-12-1949
//Got the IPNS/IPFS info from that last save ok
Clicked Start Editing

Added more space cargo boxes and a Monkey
Monkey import proved that a Blender export should be Y Up and -Z Forward

Saved again
// Scene "CarlFravelTest-2017-11-12-1949" saved to IPFS
// The IPNS locator is: /ipns/Qmcnc43usGQiXUwPNN1xoTV9MCn1Dy9mqbsqpmcwx25FUc
// The IPFS hash pointed to is: QmQkZUveT4jVjnRiGivEQdX6nQjUCY8vM2acgAt3ThWtoZ

Opened scene
Everything is there
